### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#162]
A full multiplayer mode can only implemented if we redo like 90% of the game. So impossible currently. We can think about it during the design phase of CM2 (if we somehow manage to live up to that point)

Major obstacles
- almost all code assumes there is exactly 1 SM chapter
- factions are hardcoded, with player chapter always having index 0. This means we would also have to rework factions
- factions (apart from player SM) don't actually get turns. After ending your turn, objects and data are simply processed in a haphazard way by various scripts. This would have to be reworked to actually give each faction a turn to do their actions, or at least allow each player faction.
- certainly there are more, but even the obstacles mentioned so far make it impossible to implement MP without a total rewrite.

After resolving the above we then could start to implement multiplayer.

But what about hotseat mode at least?
- same issues as for full MP, except the MP implementation phase would be easier, additional players could be simply additional factions. No need to send external requests or anything.

**Comment by Blogaugis** [comment]
> factions (apart from player SM) don't actually get turns. After ending your turn, objects and data are simply processed in a haphazard way by various scripts. This would have to be reworked to actually give each faction a turn to do their actions, or at least allow each player faction.

Which means, that playing as a different faction (not necessarily even one of imperials) also requires a CM2 tier rework.

**Comment by GalacticChimp** [comment]
> Which means, that playing as a different faction (not necessarily even one of imperials) also requires a CM2 tier rework.

maybe not a CM2 tier rework, but it will be a big project to allow playing as a different (i.e. non SM) faction
