### ISSUE TITLE
Add build and deployment pipelines

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#175]
Finishing this task will trivialize creating new packages and dramatically reduce workload for @ZAB909 before, during and after every release. Optimally, one button press will build, zip and upload a new package.

- [ ] setup build pipeline (should result in easily produceable CM.zip files)
  - [ ] add build pipeline in Actions
  - [ ] setup the build pipeline
  - [ ] add secret management, which will supply GM license data to the build agent (need help from @ZAB909 to setup repo), without exposing any password, etc data
  - [ ] zip the build contents
  - [ ] copy zip to Github's releases
  - [ ] clean up
- [ ] setup deployment pipeline
  - [ ] upload zip to file-sharing service
- [ ] if #201 works, then plugin tests into the pipeline

**Comment by renatosilvatimebel** [comment]
maybe you can trigger the pipeline when creating a Tag, that way there is no need to keep old releases on branches and you can add release notes comparing commits/merges from the latest tag and current tag (v0.8.2.1 vs 0.8.3.0). idk, just an idea

**Comment by GalacticChimp** [comment]
> maybe you can trigger the pipeline when creating a Tag, that way there is no need to keep old releases on branches and you can add release notes comparing commits/merges from the latest tag and current tag (v0.8.2.1 vs 0.8.3.0). idk, just an idea

hmm, interesting idea, I'll look into it once I start this task
