### ISSUE TITLE
Explore Marine <-> Dreadnought relationship

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#218]
**Description**

Explore a few topics:
- how can Dreadnoughts themselves be more interesting and fun?
- is it feasible and interesting to keep a Marine's stats/personality/etc after converting him to a Dreadnought?
- is it a good/fun idea to allow converting Chapter Masters to Dreadnoughts?

**Additional Information**

Lore specifies at least 1 Chapter Master being interned within a Dreadnought, [Bjorn the Fell-Handed](https://warhammer40k.fandom.com/wiki/Bjorn_the_Fell-Handed)

**Comment by renatosilvatimebel** [comment]
this is something to keep in mind, a Dreadnought its a former astartes so good, but so good, that the chapter can't afford him to die, so they slap him into a automated coffin of awesomeness with a fuckload of guns.

so it cannot be just an ordinary marine, it needs to be hero class stats. i have dreadnoughts with 80hp and lower overall stats than some of my top scouts.

**Comment by Blogaugis** [comment]
> how can Dreadnoughts themselves be more interesting and fun?

One way I see would be to let dreadnoughts also be part of HQ - like being master apothecaries, techmarines and other leaders.
In lore though, most chapters tend to make them go to sleep, only waking them up when the need arises (except Iron hands), so they are combat-only units, mostly.
Would also be nice to allow them participate in purges.
Allowing them to board in naval combat... is also interesting consideration.
> is it feasible and interesting to keep a Marine's stats/personality/etc after converting him to a Dreadnought?

It probably should be tied to bionics the marine had. If the marine had a lot of bionics, it should probably retain a lot, as it also is a mechanical part.
Whereas if the marine is shoved into a dreadnought without any bionics, I suppose it is a fair guess that their personality/experiences are reset, in a larger or smaller way?
> is it a good/fun idea to allow converting Chapter Masters to Dreadnoughts?

I'd be for it.
Though, that depends on how succession system (how the game goes on after the current chapter master or chapter as a whole is destroyed, and a new one takes it's place) is going to be implemented.
